import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hendra Agil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col text-center justify-center text-brand-blue bg-brand-dark h-screen">
        <h1 className="text-3xl font-bold">Coming Soon...</h1>
      </main>
    </>
  )
}
