import Head from 'next/head'
import { Navbar } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hendra Agil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="flex h-screen flex-col justify-center text-center">
        <h1 className="text-3xl font-bold">Coming Soon...</h1>
      </main>
    </>
  )
}
